-- oracle
-- https://school.programmers.co.kr/learn/courses/30/lessons/133026

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF NATURAL JOIN ICECREAM_INFO
GROUP BY INGREDIENT_TYPE