SELECT ANIMAL_ID,NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT DISTINCT(AI.ANIMAL_ID)
    FROM ANIMAL_INS AS AI INNER JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID) 
ORDER BY ANIMAL_ID,NAME


-- NOT IN 조건을 이용하여 차집합 수행 