SELECT HOUR(DATETIME) AS HOUR, COUNT(DATE_FORMAT(DATETIME,'%h')) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR ASC

-- HOUR라는 함수를 통해 시각 데이터의 시간을 구할 수 있다. 