WITH RECURSIVE T1 AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 
    FROM T1 
    WHERE HOUR<23)

SELECT T1.HOUR, IFNULL (T2.COUNT,0) AS COUNT
FROM T1 LEFT JOIN ( SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
                  FROM ANIMAL_OUTS 
                  GROUP BY HOUR(DATETIME)) AS T2 ON T1.HOUR = T2.HOUR